const ACTIONS = {
    VIEWCART : "VIEWCART",
    COUNT : "COUNT",
    DECREASE : "DECREASE",
    CHECK : "CHECK",
    UNCHECK : "UNCHECK",
    GET_USER : "GET_USER",
    DELETE_USER : "DELETE_USER",
    ISLOGGED:"ISLOGGED",
    ISNOTLOGGED:"ISNOTLOGGED",
    GET_TOKEN:"GET_TOKEN",
    DELETE_TOKEN:"DELETE_TOKEN",
    ISLOAD :"ISLOAD",
    LOGINWITH:{FACEBOOK : "FACEBOOK", INSTAGRAM : "INSTAGRAM", TWITTER : "TWITTER"},
    UNLOGINWITH:{UNFACEBOOK : "UNFACEBOOK", UNINSTAGRAM : "UNINSTAGRAM", UNTWITTER : "UNTWITTER"}
}
export default ACTIONS